import logging
import os

from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from airflow.sdk.exceptions import AirflowFailException

logger = logging.getLogger(__name__)

def list_bucket_files(conn_id: str, bucket_name: str, file_prefix: str | None = None,
                      file_extension: str | None = None) -> list:
    """Get a list of files for a given bucket"""

    bucket_name = bucket_name.strip()

    hook = S3Hook(aws_conn_id=conn_id)

    if not hook.check_for_bucket(bucket_name=bucket_name):
        raise AirflowFailException(f"Bucket {bucket_name} was not found.")

    prefix = file_prefix.strip() if file_prefix else ""
    extension = file_extension.strip() if file_extension else ""

    keys = hook.list_keys(bucket_name=bucket_name, prefix=prefix)
    
    if keys is None:
        return []

    return [key for key in keys if key.lower().endswith(extension.lower())]


def download_single_s3_file(file_key: str, conn_id: str, bucket_name: str, dest_dir: str) -> str:
    """
    Downloads a single file from S3 to a local directory.
    Returns the absolute path to the downloaded local file.
    """

    timeout_settings = {
        "connect_timeout": 60,
        "read_timeout": 300
    }
    
    hook = S3Hook(aws_conn_id=conn_id, config=timeout_settings)
    logger.info("Going to download file: %s", file_key)
    
    local_file_name = os.path.basename(file_key)
    local_output_path = os.path.join(dest_dir, local_file_name)
    
    try:
        hook.download_file(
            key=file_key,
            bucket_name=bucket_name,
            local_path=dest_dir,
            preserve_file_name=True,
            use_autogenerated_subdir=False  
        )
        logger.warning("Successfully saved file to: %s", local_output_path)
        return local_output_path
        
    except Exception as ex:
        if os.path.exists(local_output_path):
            logger.error("File exists. Will not download: %s", local_output_path)
        raise RuntimeError(f"Failed to download {file_key}: {str(ex)}") from ex
