services:
  airflow-apiserver:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  airflow-cli:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  airflow-dag-processor:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  airflow-init:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  airflow-scheduler:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  airflow-triggerer:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  airflow-worker:
    build: !reset
    develop: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset

  flower: !reset
