import os
import pytest
from unittest.mock import MagicMock, patch
from airflow.sdk.exceptions import AirflowFailException
from mokelumne.util.s3_utils import list_bucket_files, download_single_s3_file

# =====================================================================
# Tests for list_bucket_files
# =====================================================================

@patch("mokelumne.util.s3_utils.S3Hook")
def test_list_bucket_files_bucket_not_found(mock_s3_hook):
    """Should raise AirflowFailException if the S3 bucket does not exist."""
    mock_hook_instance = MagicMock()
    mock_hook_instance.check_for_bucket.return_value = False
    mock_s3_hook.return_value = mock_hook_instance

    with pytest.raises(AirflowFailException) as exc_info:
        list_bucket_files(bucket_name=" missing-bucket ", conn_id="aws_s3_conn")
        
    assert "Bucket missing-bucket was not found." in str(exc_info.value)
    mock_hook_instance.check_for_bucket.assert_called_once_with(bucket_name="missing-bucket")


@patch("mokelumne.util.s3_utils.S3Hook")
def test_list_bucket_files_empty_or_none_keys(mock_s3_hook):
    """Should return an empty list if list_keys returns None."""
    mock_hook_instance = MagicMock()
    mock_hook_instance.check_for_bucket.return_value = True
    mock_hook_instance.list_keys.return_value = None
    mock_s3_hook.return_value = mock_hook_instance

    result = list_bucket_files(bucket_name="my-bucket", conn_id="aws_s3_conn")
    
    assert result == []
    mock_hook_instance.list_keys.assert_called_once_with(bucket_name="my-bucket", prefix="")


@patch("mokelumne.util.s3_utils.S3Hook")
def test_list_bucket_files_with_filters(mock_s3_hook):
    """Should clean parameters and filter files by case-insensitive extension."""
    mock_hook_instance = MagicMock()
    mock_hook_instance.check_for_bucket.return_value = True
    mock_hook_instance.list_keys.return_value = [
        "data/file.wav",
        "data/file2.wav",
        "data/file.mp3",
        "data/image.png",
        "data/readme.txt"
    ]
    mock_s3_hook.return_value = mock_hook_instance

    result = list_bucket_files(
        bucket_name="my-bucket ",
        file_prefix=" data/ ",
        file_extension=" .wav",
        conn_id="custom_conn" # Kept custom string
    )
    
    assert result == ["data/file.wav", "data/file2.wav"]
    mock_s3_hook.assert_called_once_with(aws_conn_id="custom_conn")
    mock_hook_instance.list_keys.assert_called_once_with(bucket_name="my-bucket", prefix="data/")


# =====================================================================
# Tests for download_single_s3_file
# =====================================================================

@patch("mokelumne.util.s3_utils.S3Hook")
def test_download_single_s3_file_success(mock_s3_hook, tmp_path):
    """Should correctly invoke S3Hook download and return the local path."""
    mock_hook_instance = MagicMock()
    mock_s3_hook.return_value = mock_hook_instance
    
    dest_dir = str(tmp_path)
    file_key = "reports/daily_report.docx"
    expected_output_path = os.path.join(dest_dir, "daily_report.docx")

    result = download_single_s3_file(
        file_key=file_key,
        bucket_name="my-bucket",
        dest_dir=dest_dir,
        conn_id="custom_conn" # Kept custom string
    )
    
    assert result == expected_output_path
    mock_s3_hook.assert_called_once_with(
        aws_conn_id="custom_conn",
        config={"connect_timeout": 60, "read_timeout": 300}
    )
    mock_hook_instance.download_file.assert_called_once_with(
        key=file_key,
        bucket_name="my-bucket",
        local_path=dest_dir,
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )


@patch("mokelumne.util.s3_utils.S3Hook")
@patch("mokelumne.util.s3_utils.os.path.exists")
def test_download_single_s3_file_failure_with_existing_file(mock_exists, mock_s3_hook, tmp_path):
    """Should wrap exception in a RuntimeError and check if local file exists on failure."""
    mock_hook_instance = MagicMock()
    mock_hook_instance.download_file.side_effect = Exception("S3 Network Timeout")
    mock_s3_hook.return_value = mock_hook_instance
    mock_exists.return_value = True

    with pytest.raises(RuntimeError) as exc_info:
        download_single_s3_file(
            file_key="path/to/data.json",
            bucket_name="my-bucket",
            dest_dir=str(tmp_path),
            conn_id="aws_s3_conn" 
        )
        
    assert "Failed to download path/to/data.json: S3 Network Timeout" in str(exc_info.value)
    mock_exists.assert_called_once_with(os.path.join(str(tmp_path), "data.json"))
